# Generated by Django 6.0.6 on 2026-06-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firebase_uid',
        ),
    ]
