# Generated by Django 6.0.6 on 2026-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase user UID for phone authentication', max_length=128, null=True, unique=True),
        ),
    ]
