# Generated by Django 6.0.6 on 2026-06-18 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='Used in detail page only', null=True, upload_to='services/detail/'),
        ),
        migrations.AddField(
            model_name='service',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Used in cards and listing', null=True, upload_to='services/preview/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('home', 'Home Visit'), ('salon', 'In Salon'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Category icon', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for display on home page'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Show this category on home page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both')], default='both', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(help_text='Services included in this package', to='services.service')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Step',
                'verbose_name_plural': 'Service Steps',
                'ordering': ['service', 'step_number'],
            },
        ),
    ]
