# Generated by Django 6.0.6 on 2026-06-17 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salon/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='salon/')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter valid phone number')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon Info',
                'verbose_name_plural': 'Salon Info',
            },
        ),
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_booking_days', models.PositiveIntegerField(default=30, help_text='How many days in advance customers can book')),
                ('min_booking_notice_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours notice required for booking')),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours before appointment to cancel')),
                ('max_bookings_per_slot', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_online_payment', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon Settings',
                'verbose_name_plural': 'Salon Settings',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'unique_together': {('day',)},
            },
        ),
    ]
