# Generated by Django 6.0.6 on 2026-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_booking_payment_booking_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
