# Generated by Django 6.0.6 on 2026-06-29 11:04

from django.db import migrations

def map_old_statuses(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.filter(status__in=['pending', 'payment_confirmed']).update(status='confirmed')
    Booking.objects.filter(status='no_show').update(status='cancelled')

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.RunPython(map_old_statuses, migrations.RunPython.noop),
    ]