# Generated by Django 6.0.6 on 2026-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_simplify_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('change_of_plans', 'Change of plans'), ('booked_wrong_slot', 'Booked wrong date/time'), ('found_better_price', 'Found a better price elsewhere'), ('professional_unavailable', 'Professional/slot unavailable'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
