# Generated by Django 6.0.6 on 2026-06-30 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_cancellation_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_type', models.CharField(choices=[('salon', 'In Salon'), ('home', 'Home Visit')], default='salon', max_length=10)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_area', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('change_of_plans', 'Change of plans'), ('booked_wrong_slot', 'Booked wrong date/time'), ('found_better_price', 'Found a better price elsewhere'), ('professional_unavailable', 'Professional/slot unavailable'), ('other', 'Other')], max_length=30, null=True)),
                ('cancellation_note', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Group',
                'verbose_name_plural': 'Booking Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.bookinggroup'),
        ),
    ]
