# Generated by Django 6.0.6 on 2026-07-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookinggroup_booking_group'),
        ('services', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Set when this service-booking came from a Package rather than being booked standalone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.package'),
        ),
    ]
